export const Session =
{
    MeterType: "METER_TYPE",
    Name: "NAME",
    AccountNumber: "ACCOUNT_NUMBER",
    UserID: "UserID",
    Email: "Email",
    BPNumber: "BPNumber",
    AccountAddress: "AccountAddress",
    Address1: "Address1",
    Address2: "Address2",
    City: "City",
    State: "State",
    Country:"Country",
    PostalCode: "PostalCode",
    IPAddress: "IPAddress",
    FirstName: "FirstName",
    LastName: "LastName",
    MiddleName: "MiddleName",
    FullName: "FullName",
    ServiceAddressPremiseId: "ServiceAddressPremiseId",
    BrowserDeviceID: "BrowserDeviceID",
    TwoFactorAuthenticated: "TwoFactorAuthenticated",
    InboxUnreadCount: "InboxUnreadCount",
    MobileNumber: "MobileNumber",
    AccountType: 'AccountType',
    AccountId: 0,
    ServiceAddress: 'ServiceAddress',
    AccountStatus:'AccountStatus',
    IsMigratedUser: 'IsMigratedUser',
    SessionId : 'SessionId',
    WorkflowGUID: 'WorkflowGUID',
    CustomerType: 'CustomerType',
    RoleId: 'RoleId',
    AllowAsPreLoginAPI: "false",
    AccessToken : "AccessToken"
}
// export default Session;
